/* 设计预览使用统一示例数据，不发起禅道网络请求。 */
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const ico = name => `<i data-lucide="${esc(name)}"></i>`;
window.esc = esc; window.ico = ico;
const APP_VERSION = '0.1.0';
document.getElementById('brand-version').textContent = `v${APP_VERSION}`;
const statuses = {todo:'待做',doing:'正在做',done:'已完成',closed:'已关闭'};
const statusIcons = {todo:'circle-dashed',doing:'circle-dot',done:'circle-check',closed:'circle-x'};
const priorities = {high:'高优先级',normal:'普通',low:'低优先级'};
const initialTasks = [
 {id:'T-101',title:'梳理客户门户改版需求',source:'personal',status:'todo',priority:'high',date:'2026-09-07',time:'09:00',end:'10:00',due:'2026-09-07',project:'客户门户',notes:'整理本轮改版范围，补充登录、工作台和权限配置的需求清单。',sub:'整理需求清单，确认本轮迭代范围'},
 {id:'T-102',title:'准备周三产品评审材料',source:'personal',status:'todo',priority:'normal',date:'2026-09-09',time:'10:00',end:'11:30',due:'2026-09-09',project:'产品规划',notes:'汇总原型与验收标准，整理尚待确认的问题。',sub:'汇总原型与验收标准'},
 {id:'E-240',title:'数据服务 · 九月迭代',source:'zentao',status:'todo',priority:'normal',date:'2026-09-10',time:'',due:'2026-09-18',project:'数据服务',remote:'未开始',notes:'关注接口字段变更和前后端联调排期。',sub:'接口梳理与数据质量优化'},
 {id:'T-104',title:'整理开发环境配置文档',source:'personal',status:'todo',priority:'low',date:'',time:'',due:'',project:'团队协作',notes:'记录新同事需要的环境、依赖与本地启动步骤。',sub:'补全环境变量与本地启动步骤'},
 {id:'E-238',title:'客户门户 · 第二期迭代',source:'zentao',status:'doing',priority:'high',date:'2026-09-07',time:'10:30',end:'12:00',due:'2026-09-11',project:'客户门户',remote:'进行中',notes:'今天先确认工作台模块的接口边界，下午跟进联调问题。',sub:'工作台与权限管理模块联调'},
 {id:'T-106',title:'完成工作台首页交互设计',source:'personal',status:'doing',priority:'normal',date:'2026-09-07',time:'14:00',end:'16:00',due:'2026-09-08',project:'个人工作台',notes:'完成总览、任务看板与日历三种工作场景的交互串联。',sub:'总览、任务看板与日历体验'},
 {id:'T-107',title:'排查登录会话过期问题',source:'personal',status:'doing',priority:'high',date:'2026-09-07',time:'16:30',end:'17:30',due:'2026-09-06',project:'客户门户',notes:'复现会话过期后的异常跳转，确认重新登录后的恢复行为。',sub:'复现异常并补充回归验证'},
 {id:'E-231',title:'运维平台 · 监控接入',source:'zentao',status:'doing',priority:'normal',date:'2026-09-08',time:'11:00',end:'12:00',due:'2026-09-15',project:'运维平台',remote:'进行中',notes:'确认告警规则与指标采集范围。',sub:'服务指标采集与告警规则配置'},
 {id:'T-109',title:'同步本周工作计划',source:'personal',status:'done',priority:'normal',date:'2026-09-07',time:'08:30',end:'09:00',due:'2026-09-07',project:'团队协作',notes:'本周安排已整理。',sub:'已整理本周重点与时间安排'},
 {id:'E-226',title:'基础服务 · 认证升级',source:'zentao',status:'done',priority:'normal',date:'2026-09-04',time:'15:00',end:'16:00',due:'2026-09-04',project:'基础服务',remote:'已完成',notes:'认证联调和验收已完成。',sub:'登录认证联调与验收已完成'},
 {id:'T-111',title:'整理八月项目复盘',source:'personal',status:'done',priority:'low',date:'2026-09-03',time:'14:00',end:'15:00',due:'2026-09-03',project:'团队协作',notes:'复盘内容已归档。',sub:'交付记录与改进事项归档'},
 {id:'T-112',title:'调研旧版报表迁移方案',source:'personal',status:'closed',priority:'low',date:'2026-09-02',time:'',due:'',project:'数据服务',notes:'本轮不再迁移旧版，改为统一建设新报表。',sub:'方案调整，当前任务不再继续'},
].map(task=>({end:'',...task}));
let tasks = projectStore.bindInitialTasks(structuredClone(initialTasks));
let projectFilter='all';
function projectOptions(selected,includeAll=false){return `${includeAll?'<option value="all">全部项目</option>':''}<option value="">未关联项目</option>${['local','zentao'].map(source=>`<optgroup label="${source==='local'?'本地项目':'禅道项目'}">${projectStore.projects.filter(p=>p.source===source).map(p=>`<option value="${esc(p.id)}" ${p.id===selected?'selected':''}>${esc(p.name)}${source==='zentao'?` · 禅道 #${p.remoteId}`:''}</option>`).join('')}</optgroup>`).join('')}`;}
function openProjectTasks(id){projectFilter=id;taskView='board';sourceFilter='all';statusFilter='all';priorityFilter='all';window.searchTerm='';document.getElementById('global-search').value='';closeOverlay();if(route==='tasks')render();else navigate('tasks');}
function taskProjectField(t){const p=projectStore.find(t.projectId);return `<div class="drawer-field"><label for="detail-project">${ico('folder-kanban')}所属项目</label>${t.source==='zentao'?`<div class="task-project-readonly"><button type="button" class="text-btn" data-action="project-tasks" data-id="${esc(t.projectId)}">${esc(p?.name||'项目暂不可访问')}${ico('arrow-up-right')}</button><small>禅道项目 #${t.remoteProjectId} · 关联随禅道同步</small></div>`:`<select name="projectId" id="detail-project" class="field-input">${projectOptions(t.projectId)}</select>`}</div>`;}
window.projectTaskAPI={getTasks:()=>tasks,openTasks:openProjectTasks,createTask:(id)=>newTask('todo',id),openTask:(id)=>detail(id)};
let route = 'overview', taskView = 'board', sourceFilter = 'all', statusFilter = 'all', priorityFilter='all', overviewTab='today';
let selectedDate='2026-09-07', month=8, year=2026, calendarMode='month', calendarSources={personal:true,zentao:true};
let lastFocus=null, toastTimer=null, undoAction=null, managementEnabled=false;
window.appCategory='全部';window.searchTerm='';
const main=document.getElementById('main');
const today='2026-09-07';
function icons(){lucide.createIcons({attrs:{'stroke-width':1.7}});}
function remoteStatusClass(status){return ({'未开始':'todo','进行中':'doing','已完成':'done','已关闭':'closed','已暂停':'todo'})[status]||'todo';}
function sourceLabel(task){return `<span class="source ${task.source}">${ico(task.source==='zentao'?'waypoints':'circle-user-round')}${task.source==='zentao'?'禅道执行':'个人任务'}${task.source==='zentao'?` · #${task.id.slice(2)}`:''}</span>`;}
function tag(task){return `<span class="tag ${task.status}">${statuses[task.status]}</span>`;}
function isOverdue(t){return t.due && t.due<today && !['done','closed'].includes(t.status);}
function dateLabel(date){return !date?'未排期':date===today?'今天':`${Number(date.slice(5,7))}月${Number(date.slice(8))}日`;}
function timeRange(task){return task.time ? task.end ? `${task.time}–${task.end}` : task.time : '';}
function scheduleLabel(task){const range=timeRange(task);return `${dateLabel(task.date)}${range?` ${range}`:''}`;}
function validateSchedule(date,start,end){
 if((start||end)&&!date)return '设置时间前，请先选择计划日期';
 if(end&&!start)return '设置结束时间前，请先选择开始时间';
 if(start&&end&&end<=start)return '结束时间必须晚于开始时间';
 return '';
}
function iso(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function count(status){return tasks.filter(t=>t.status===status).length;}
function filteredTasks(){return tasks.filter(t=>(projectFilter==='all'||(t.projectId||'')===projectFilter)&&(sourceFilter==='all'||t.source===sourceFilter)&&(statusFilter==='all'||t.status===statusFilter)&&(priorityFilter==='all'||t.priority===priorityFilter)&&`${t.title} ${t.project} ${t.id}`.toLowerCase().includes(window.searchTerm.toLowerCase()));}
function navigate(name){location.hash=name;}
function render(){
 if(projectFilter&&projectFilter!=='all'&&!projectStore.find(projectFilter))projectFilter='all';
 tasks.forEach(t=>{t.project=projectStore.find(t.projectId)?.name||'未关联项目';});
 const labels={overview:'总览',projects:'项目',tasks:'我的任务',calendar:'日历',apps:'应用',settings:'设置与连接',models:'大模型管理',agents:'Agent',skills:'技能',knowledge:'知识库',chat:'聊天'};
 document.getElementById('page-crumb').textContent=labels[route];
 const scopedSearch=['models','agents','settings'].includes(route);
 document.querySelector('.global-search').style.display=scopedSearch?'none':'';
 document.querySelector('.demo-label').style.marginLeft=scopedSearch?'auto':'';
 document.getElementById('global-search').placeholder=route==='chat'?'搜索会话与消息':route==='projects'?'搜索项目、描述或负责人':route==='skills'?'搜索技能':route==='knowledge'?'搜索知识库或文档':'搜索任务、执行或应用';
 document.getElementById('navigation').innerHTML=[['overview','house','总览'],['projects','folder-kanban','项目'],['tasks','square-check-big','我的任务'],['calendar','calendar-days','日历'],['apps','layout-grid','应用'],['agents','bot','Agent'],['skills','puzzle','技能'],['knowledge','library','知识库'],['chat','messages-square','聊天']].map(([key,icon,label])=>`<a class="nav-item ${route===key?'active':''}" href="#${key}">${ico(icon)}<span>${label}</span>${key==='tasks'?`<span class="count">${tasks.filter(t=>['todo','doing'].includes(t.status)).length}</span>`:''}</a>`).join('');
 document.getElementById('personal-count').textContent=tasks.filter(t=>t.source==='personal').length;
 document.getElementById('zentao-count').textContent=tasks.filter(t=>t.source==='zentao').length;
 main.classList.toggle('chat-page',route==='chat');
 main.innerHTML=route==='overview'?overviewPage():route==='projects'?projectPages.render():route==='tasks'?tasksPage():route==='calendar'?calendarPage():route==='apps'?secondaryPages.apps():route==='models'?modelPages.render():route==='agents'?agentPages.render():route==='skills'?skillPages.render():route==='knowledge'?knowledgePages.render():route==='chat'?chatPages.render():secondaryPages.settings();
 if(route==='tasks'){
   document.querySelector('.task-toolbar .toolbar-left').insertAdjacentHTML('beforeend',`<select class="filter-select task-project-filter" id="project-filter" aria-label="筛选项目">${projectOptions(projectFilter,true)}</select>`);
   document.getElementById('project-filter').value=projectFilter;
   const visible=filteredTasks();document.querySelectorAll('.task-table tbody tr').forEach((row,i)=>row.children[1].insertAdjacentHTML('beforeend',`<small class="task-list-project">${esc(visible[i].project)}</small>`));
 }
 document.querySelector('.sidebar-bottom .nav-item').classList.toggle('active',['settings','models'].includes(route));
 if(route==='settings')document.getElementById('management-toggle').checked=managementEnabled;
 icons();
}
function miniCalendar(){
 const offset=(new Date(year,month,1).getDay()+6)%7;
 const days=new Date(year,month+1,0).getDate();
 const cells=Math.ceil((offset+days)/7)*7;
 return `<div class="mini-month-title"><span>${year}年 ${month+1}月</span><div><button class="icon-btn" data-action="month-prev" title="上个月" aria-label="上个月">${ico('chevron-left')}</button><button class="icon-btn" data-action="month-next" title="下个月" aria-label="下个月">${ico('chevron-right')}</button></div></div><div class="mini-week">${['一','二','三','四','五','六','日'].map(x=>`<span>${x}</span>`).join('')}</div><div class="mini-days">${Array.from({length:cells},(_,i)=>{const d=new Date(year,month,i-offset+1),key=iso(d);return `<button class="mini-day ${d.getMonth()!==month?'other':''} ${key===today?'today':''} ${tasks.some(t=>t.date===key)?'has-task':''}" data-action="select-date" data-date="${key}" aria-label="${key}">${d.getDate()}</button>`;}).join('')}</div>`;
}
function row(t){return `<div class="task-row"><button class="check-button ${t.status==='done'?'checked':''}" data-action="complete" data-id="${t.id}" aria-label="${t.status==='done'?'重新打开':'完成'} ${esc(t.title)}">${t.status==='done'?ico('check'):''}</button><div class="task-row-main" role="button" tabindex="0" data-action="detail" data-id="${t.id}"><strong>${esc(t.title)}</strong><div class="row-meta">${sourceLabel(t)}<span>·</span><span>${esc(t.project)}</span></div></div>${t.priority==='high'?'<span class="tag priority-high">高</span>':''}${tag(t)}<time class="row-time">${timeRange(t)||'全天'}</time></div>`;}
function overviewPage(){
 const todays=tasks.filter(t=>t.date===selectedDate&&!['closed'].includes(t.status)).sort((a,b)=>(a.time||'').localeCompare(b.time||''));
 const visible=(overviewTab==='today'?todays:overviewTab==='overdue'?tasks.filter(isOverdue):tasks.filter(t=>t.status==='doing')).filter(t=>t.title.toLowerCase().includes(window.searchTerm.toLowerCase()));
 const quick=window.demoApps.filter(a=>a.favorite).slice(0,4);
 return `<div class="page-heading"><div><h1>总览</h1><p>把今天的事情，安排得井井有条。</p></div><span class="date-text">${ico('calendar-days')}2026年9月7日 · 星期一</span></div>
 <div class="summary-strip">${Object.entries(statuses).map(([key,label])=>`<button class="summary-item" data-action="status-filter" data-value="${key}"><div><span class="metric-title">${ico(statusIcons[key])}${label}</span><strong>${count(key)}</strong></div><span class="metric-note ${key==='doing'?'urgent':''}">${key==='doing'?`${tasks.filter(isOverdue).length} 项已逾期`:key==='todo'?`${tasks.filter(t=>t.status==='todo'&&!t.date).length} 项未排期`:key==='done'?'已完成事项':'不再继续'}</span></button>`).join('')}</div>
 <div class="overview-grid"><div><section><div class="section-heading"><h2>今日任务 <span class="muted">${todays.length}</span></h2><button class="text-btn" data-action="go-tasks">全部任务 ${ico('arrow-up-right')}</button></div><div class="section-tabs"><button data-action="overview-tab" data-value="today" class="${overviewTab==='today'?'active':''}">今日安排</button><button data-action="overview-tab" data-value="overdue" class="${overviewTab==='overdue'?'active':''}">逾期 <span class="muted">${tasks.filter(isOverdue).length}</span></button><button data-action="overview-tab" data-value="doing" class="${overviewTab==='doing'?'active':''}">正在做</button></div>${visible.map(row).join('')||'<div class="empty">当前没有任务</div>'}</section>
 <section class="bottom-section"><div class="section-heading"><h2>常用应用</h2><button class="text-btn" data-action="go-apps">全部应用 ${ico('arrow-up-right')}</button></div><div class="quick-apps">${quick.map(a=>`<a class="quick-app" href="${esc(a.url)}" target="_blank" rel="noopener noreferrer"><span class="app-symbol ${a.id}">${a.logo?`<img src="${esc(a.logo)}" alt="${esc(a.name)} 标志">`:esc(a.name.slice(0,1))}</span><div><strong>${esc(a.name)}</strong><small>${esc(a.category||'未分类')}</small></div></a>`).join('')}</div></section>
 <section class="bottom-section"><div class="section-heading"><h2>关注的执行 <span class="muted">${tasks.filter(t=>t.source==='zentao').length}</span></h2><button class="text-btn" data-action="source" data-source="zentao">查看全部 ${ico('arrow-up-right')}</button></div>${tasks.filter(t=>t.source==='zentao'&&t.status==='doing').map(t=>`<div class="execution-row"><span class="app-symbol zentao">${ico('waypoints')}</span><div role="button" tabindex="0" data-action="detail" data-id="${t.id}"><strong>${esc(t.title)}</strong><small>禅道执行 #${t.id.slice(2)} · 截止 ${dateLabel(t.due)}</small></div>${tag(t)}<button class="icon-btn" data-action="detail" data-id="${t.id}" title="查看执行详情" aria-label="查看 ${esc(t.title)}">${ico('chevron-right')}</button></div>`).join('')}</section></div>
 <aside class="overview-rail">${miniCalendar()}<div class="agenda"><div class="agenda-title"><b>${dateLabel(selectedDate)}安排</b><span>${todays.length} 项</span></div>${todays.slice(0,4).map(t=>`<div class="agenda-item"><span>${t.time||'全天'}</span><div role="button" tabindex="0" data-action="detail" data-id="${t.id}"><strong>${esc(t.title)}</strong><small>${timeRange(t)||'全天'} · ${t.source==='zentao'?'禅道执行':'个人任务'}</small></div></div>`).join('')||'<p class="muted">这一天暂无安排</p>'}</div><button class="text-btn" data-action="go-calendar">打开日历 ${ico('arrow-right')}</button></aside></div>`;
}
function taskCard(t){const range=timeRange(t);return `<article class="task-card" draggable="true" data-task-id="${t.id}" data-action="detail" data-id="${t.id}" tabindex="0" aria-label="${esc(t.title)}，${statuses[t.status]}"><div class="card-top">${sourceLabel(t)}<button class="icon-btn" data-action="detail" data-id="${t.id}" title="任务详情" aria-label="任务详情">${ico('ellipsis')}</button></div><h3>${esc(t.title)}</h3><p class="description">${esc(t.sub)}</p><div class="card-labels">${t.priority==='high'?'<span class="tag priority-high">高优先级</span>':''}<span class="tag">${esc(t.project)}</span></div><div class="card-footer"><span class="${isOverdue(t)?'overdue':''}">${ico(isOverdue(t)?'circle-alert':'calendar-days')}${isOverdue(t)?`逾期 1 天${range?` · ${range}`:''}`:scheduleLabel(t)}</span><span class="avatar">我</span></div></article>`;}
function tasksPage(){
 const filtered=filteredTasks();
 const toolbar=`<div class="task-toolbar"><div class="toolbar-left"><div class="segmented"><button class="${taskView==='board'?'active':''}" data-action="task-view" data-value="board">${ico('columns-3')}看板</button><button class="${taskView==='list'?'active':''}" data-action="task-view" data-value="list">${ico('list')}列表</button></div><select class="filter-select" id="source-filter" aria-label="任务来源">${[['all','全部来源'],['personal','个人任务'],['zentao','禅道执行']].map(([v,l])=>`<option value="${v}" ${v===sourceFilter?'selected':''}>${l}</option>`).join('')}</select><select class="filter-select" id="status-filter" aria-label="任务状态"><option value="all">全部状态</option>${Object.entries(statuses).map(([v,l])=>`<option value="${v}" ${v===statusFilter?'selected':''}>${l}</option>`).join('')}</select></div><div class="toolbar-right"><span class="muted" style="font-size:11px">${filtered.length} 个任务</span><select class="filter-select" id="priority-filter" aria-label="优先级"><option value="all">全部优先级</option>${Object.entries(priorities).map(([v,l])=>`<option value="${v}" ${v===priorityFilter?'selected':''}>${l}</option>`).join('')}</select></div></div>`;
 return `<div class="page-heading"><div><h1>我的任务</h1><p>每一步进展，都在这里。</p></div><button class="btn" data-action="go-calendar">${ico('calendar-days')}日历视图</button></div>${toolbar}${taskView==='board'?`<div class="board">${Object.entries(statuses).map(([key,label])=>`<section class="board-column" data-drop-status="${key}" aria-label="${label}"><div class="column-head ${key}">${ico(statusIcons[key])}${label}<span class="column-count">${filtered.filter(t=>t.status===key).length}</span><button class="icon-btn" data-action="new-task" data-status="${key}" title="添加${label}任务" aria-label="添加${label}任务">${ico('plus')}</button></div>${filtered.filter(t=>t.status===key).map(taskCard).join('')}<button class="add-column-task" data-action="new-task" data-status="${key}">${ico('plus')}添加任务</button></section>`).join('')}</div>`:`<div class="table-wrap"><table class="task-table"><thead><tr><th></th><th>任务名称</th><th>来源</th><th>状态</th><th>优先级</th><th>个人安排</th></tr></thead><tbody>${filtered.map(t=>`<tr data-action="detail" data-id="${t.id}" tabindex="0"><td><button class="check-button ${t.status==='done'?'checked':''}" data-action="complete" data-id="${t.id}" aria-label="切换 ${esc(t.title)} 完成状态">${t.status==='done'?ico('check'):''}</button></td><td>${esc(t.title)}</td><td>${sourceLabel(t)}</td><td>${tag(t)}</td><td>${t.priority==='high'?'<span class="tag priority-high">高</span>':priorities[t.priority]}</td><td>${scheduleLabel(t)}</td></tr>`).join('')}</tbody></table>${!filtered.length?'<div class="empty">没有符合筛选条件的任务</div>':''}</div>`}`;
}
function calendarTaskList(date){return tasks.filter(t=>t.date===date&&calendarSources[t.source]&&t.status!=='closed'&&t.title.toLowerCase().includes(window.searchTerm.toLowerCase())).sort((a,b)=>(a.time||'').localeCompare(b.time||''));}
function calendarPage(){
 const offset=(new Date(year,month,1).getDay()+6)%7,days=new Date(year,month+1,0).getDate();
 const cells=Math.ceil((offset+days)/7)*7;
 const grid=`<div class="month-grid">${['周一','周二','周三','周四','周五','周六','周日'].map(d=>`<div class="weekday">${d}</div>`).join('')}${Array.from({length:cells},(_,i)=>{let d=new Date(year,month,i-offset+1),key=iso(d),events=calendarTaskList(key);return `<div class="month-cell ${d.getMonth()!==month?'other':''} ${key===selectedDate?'selected':''} ${i%7>4?'weekend':''}" data-drop-date="${key}"><button class="day-number ${key===today?'today':''}" data-action="day-detail" data-date="${key}" aria-label="查看 ${key} 的任务">${d.getDate()}</button>${events.slice(0,3).map(t=>`<button class="calendar-event ${t.source} ${t.status}" data-action="detail" data-id="${t.id}" draggable="true" data-task-id="${t.id}" title="${esc(t.title)}">${timeRange(t)||'全天'} ${esc(t.title)}</button>`).join('')}${events.length>3?`<button class="calendar-more" data-action="day-detail" data-date="${key}">+${events.length-3} 项</button>`:''}</div>`;}).join('')}</div>`;
 const monthEvents=tasks.filter(t=>t.date.startsWith(`${year}-${String(month+1).padStart(2,'0')}`)&&calendarSources[t.source]&&t.status!=='closed');
 const list=`<div>${monthEvents.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(t=>`<div class="calendar-agenda-row"><time>${dateLabel(t.date)} ${timeRange(t)||'全天'}</time><button class="task-row-main" data-action="detail" data-id="${t.id}"><strong>${esc(t.title)}</strong></button>${sourceLabel(t)}${tag(t)}</div>`).join('')||'<div class="empty">本月暂无安排</div>'}</div>`;
 return `<div class="page-heading"><div><h1>日历</h1><p>给重要的事情，留出时间。</p></div></div><div class="calendar-layout"><aside class="calendar-aside">${miniCalendar()}<h3>我的日历</h3>${[['personal','个人任务','blue'],['zentao','禅道执行','amber']].map(([key,label,color])=>`<label class="calendar-source"><input type="checkbox" data-calendar-source="${key}" ${calendarSources[key]?'checked':''}>${label}<span class="dot ${color}"></span></label>`).join('')}<h3>未排期 <span class="muted">${tasks.filter(t=>!t.date).length}</span></h3>${tasks.filter(t=>!t.date).map(t=>`<button class="unscheduled" data-action="detail" data-id="${t.id}" draggable="true" data-task-id="${t.id}">${ico('grip-vertical')}${esc(t.title)}</button>`).join('')}</aside><section class="calendar-main"><div class="calendar-toolbar"><div class="toolbar-left"><button class="btn" data-action="calendar-today">今天</button><button class="icon-btn" data-action="month-prev" aria-label="上一期" title="上一期">${ico('chevron-left')}</button><button class="icon-btn" data-action="month-next" aria-label="下一期" title="下一期">${ico('chevron-right')}</button><h2>${year}年 ${month+1}月</h2></div><div class="segmented">${[['day','日'],['week','周'],['month','月'],['list','列表']].map(([key,label])=>`<button class="${calendarMode===key?'active':''}" data-action="calendar-mode" data-value="${key}">${label}</button>`).join('')}</div></div>${calendarMode==='month'?grid:calendarMode==='list'?list:timeGrid()}<div class="calendar-foot"><span class="dot blue"></span>个人任务 <span style="margin-left:12px" class="dot amber"></span>禅道执行 <span style="margin-left:auto">Asia/Shanghai</span></div></section></div>`;
}
function timeGrid(){
 const start=new Date(selectedDate+'T00:00:00');if(calendarMode==='week')start.setDate(start.getDate()-(start.getDay()+6)%7);
 const dates=Array.from({length:calendarMode==='day'?1:7},(_,i)=>{let d=new Date(start);d.setDate(d.getDate()+i);return iso(d);});
 return `<div class="week-grid ${calendarMode==='day'?'day-view':''}"><div class="week-head"></div>${dates.map(d=>`<div class="week-head">${dateLabel(d)}</div>`).join('')}${['全天',...Array.from({length:11},(_,i)=>`${String(i+8).padStart(2,'0')}:00`)].map(hour=>`<div class="week-time">${hour}</div>${dates.map(d=>`<div data-drop-date="${d}">${calendarTaskList(d).filter(t=>hour==='全天'?!t.time:t.time.slice(0,2)===hour.slice(0,2)).map(t=>`<button class="calendar-event ${t.source}" data-action="detail" data-id="${t.id}" title="${esc(t.title)}">${timeRange(t)||'全天'} ${esc(t.title)}</button>`).join('')}</div>`).join('')}`).join('')}</div>`;
}
function showToast(text,undo){clearTimeout(toastTimer);undoAction=undo;const toast=document.getElementById('toast');toast.innerHTML=`<span>${esc(text)}</span>${undo?'<button data-action="undo">撤销</button>':''}`;toast.classList.add('visible');toastTimer=setTimeout(()=>toast.classList.remove('visible'),5000);}
function changeStatus(id,status){const t=tasks.find(t=>t.id===id),old=t.status;t.status=status;render();showToast(`已移至${statuses[status]}`,()=>{t.status=old;render();});}
function openOverlay(html,modal=false){lastFocus=document.activeElement;document.getElementById('overlay-root').innerHTML=`<div class="overlay ${modal?'modal-overlay':''}">${html}</div>`;icons();requestAnimationFrame(()=>document.querySelector('.overlay button,.overlay input,.overlay select')?.focus());}
function closeOverlay(){if(window.categoryManager?.isOpen()){categoryManager.close();return;}document.getElementById('overlay-root').innerHTML='';lastFocus?.focus();}
function detail(id){const t=tasks.find(t=>t.id===id);if(!t)return;
 const remoteBadge = `<span class="tag ${remoteStatusClass(t.remote)}">${esc(t.remote)}</span>`;
 openOverlay(`<section class="drawer" role="dialog" aria-modal="true" aria-labelledby="detail-title"><div class="drawer-top"><span>任务详情 <span class="muted">/ ${t.id}</span></span><button class="icon-btn" data-action="close" title="关闭详情" aria-label="关闭详情">${ico('x')}</button></div><div class="drawer-content">${sourceLabel(t)}<h2 id="detail-title">${esc(t.title)}</h2><form id="detail-form" data-id="${t.id}"><div class="drawer-field"><label for="detail-status">${ico('circle-dot')}个人状态</label><select name="status" id="detail-status" class="field-input">${Object.entries(statuses).map(([v,l])=>`<option value="${v}" ${t.status===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="drawer-field"><label for="detail-priority">${ico('flag')}优先级</label><select name="priority" id="detail-priority" class="field-input">${Object.entries(priorities).map(([v,l])=>`<option value="${v}" ${t.priority===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="drawer-field"><label for="detail-date">${ico('calendar-days')}个人安排</label><input class="field-input" type="date" name="date" id="detail-date" value="${esc(t.date)}"></div><div class="drawer-field"><label for="detail-time">${ico('clock-3')}开始时间</label><input class="field-input" type="time" name="time" id="detail-time" value="${esc(t.time)}"></div><div class="drawer-field"><label for="detail-end">${ico('timer')}结束时间</label><input class="field-input" type="time" name="end" id="detail-end" value="${esc(t.end)}"></div><div id="detail-error" class="field-error schedule-error" role="alert"></div><div class="drawer-field"><label>${ico('calendar-check')}截止日期</label><span>${t.due?dateLabel(t.due):'未设置'}</span></div><div class="drawer-section"><h3>个人备注</h3><textarea class="field-input" name="notes" aria-label="个人备注">${esc(t.notes)}</textarea></div></form>${t.source==='zentao'?`<div class="drawer-section"><h3>禅道执行</h3><div class="remote-detail"><div><span class="muted">所属项目</span><span>${esc(t.project)}</span></div><div><span class="muted">执行编号</span><span>#${t.id.slice(2)}</span></div><div><span class="muted">禅道状态</span>${remoteBadge}</div><div><span class="muted">数据来源</span><span>示例 · 尚未同步</span></div></div><div class="remote-actions"><button class="btn" data-action="zentao-manage">${ico('external-link')}在禅道中管理</button><button class="btn" data-action="remote-preview" data-id="${t.id}">${ico('square-pen')}禅道操作</button></div><p class="drawer-help">${managementEnabled?'已开启管理入口，待连接后核验操作权限。':'管理操作尚未开启。'}个人安排独立保存。</p></div>`:''}</div><div class="drawer-bottom"><span>修改保留在本次预览中</span><button class="btn primary" data-action="save-detail" data-id="${t.id}">保存更改</button></div></section>`);
 document.getElementById('detail-form').insertAdjacentHTML('afterbegin',taskProjectField(t));icons();
}
function newTask(status='todo',projectId=projectFilter==='all'?'':projectFilter){
 openOverlay(`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="new-title"><h2 id="new-title">新建任务</h2><form id="new-task-form"><label for="new-title-input">任务名称</label><input id="new-title-input" class="field-input" name="title" placeholder="准备做什么？" required maxlength="160"><label for="new-date">计划日期</label><input id="new-date" class="field-input" name="date" type="date" value="${selectedDate}"><div class="time-field-grid"><div><label for="new-time">开始时间</label><input id="new-time" class="field-input" name="time" type="time"></div><div><label for="new-end">结束时间</label><input id="new-end" class="field-input" name="end" type="time"></div></div><div id="new-task-error" class="field-error" role="alert"></div><label for="new-status">状态</label><select id="new-status" class="field-input" name="status">${Object.entries(statuses).map(([v,l])=>`<option value="${v}" ${v===status?'selected':''}>${l}</option>`).join('')}</select><label for="new-notes">备注</label><textarea id="new-notes" class="field-input" name="notes" rows="3"></textarea><div class="modal-actions"><button type="button" class="btn" data-action="close">取消</button><button class="btn primary" type="submit">创建任务</button></div></form></section>`,true);
 document.querySelector('#new-task-form label[for="new-date"]').insertAdjacentHTML('beforebegin',`<label for="new-project">所属项目</label><select id="new-project" class="field-input" name="projectId">${projectOptions(projectId)}</select>`);
}
function appForm(id){const app=window.demoApps.find(a=>a.id===id);
 const descriptionField=`<label for="app-description">描述</label><textarea id="app-description" class="field-input" name="description" rows="3" maxlength="240" placeholder="简要说明应用用途（选填）">${esc(app?.description||'')}</textarea>`;
 openOverlay(`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="app-form-title"><h2 id="app-form-title">${app?'编辑':'添加'}应用</h2><form id="app-form" data-id="${app?.id||''}"><label for="app-name">名称</label><input id="app-name" class="field-input" name="name" required maxlength="60" value="${esc(app?.name||'')}"><label for="app-url">网址</label><input id="app-url" class="field-input" name="url" type="url" required placeholder="https://" value="${esc(app?.url||'')}">${descriptionField}<label for="app-category">分类</label><div class="app-category-control"><select id="app-category" class="field-input" name="category">${categoryManager.options(app?app.category:window.appCategories[0]||'')}</select><button type="button" class="text-btn category-manage-link" data-category-action="open">管理分类</button></div><label for="app-logo">Logo</label><input id="app-logo" class="field-input" name="logo" type="file" accept="image/png,image/jpeg,image/webp"><p>未添加 Logo 时使用名称首字。</p><div id="app-error" class="field-error" role="alert"></div><div class="modal-actions">${app?`<button type="button" class="btn danger" data-action="remove-app" data-id="${app.id}">移除</button>`:''}<button type="button" class="btn" data-action="close">取消</button><button class="btn primary" type="submit">保存</button></div></form></section>`,true);
}
document.addEventListener('click',event=>{
 const el=event.target.closest('[data-action]');
 if(!el){if(event.target.classList.contains('overlay'))closeOverlay();return;}
 const action=el.dataset.action,id=el.dataset.id,value=el.dataset.value;
 if(action==='close'){closeOverlay();return;}
 if(action==='detail'){detail(id);return;}
 if(action==='project-tasks'){openProjectTasks(id);return;}
 if(action==='new-task'){newTask(el.dataset.status);return;}
 if(action==='complete'){changeStatus(id,tasks.find(t=>t.id===id).status==='done'?'todo':'done');return;}
 if(action==='undo'){undoAction?.();document.getElementById('toast').classList.remove('visible');return;}
 if(action==='task-view'){taskView=value;render();return;}
 if(action==='overview-tab'){overviewTab=value;render();return;}
 if(action==='status-filter'){projectFilter='all';statusFilter=value;sourceFilter='all';navigate('tasks');if(route==='tasks')render();return;}
 if(action==='source'){projectFilter='all';sourceFilter=el.dataset.source;statusFilter='all';navigate('tasks');if(route==='tasks')render();return;}
 if(action.startsWith('go-')){if(action==='go-tasks')projectFilter='all';navigate(action.slice(3));return;}
 if(action==='month-prev'||action==='month-next'){const delta=action==='month-prev'?-1:1;if(route==='calendar'&&['week','day'].includes(calendarMode)){const d=new Date(selectedDate+'T00:00:00');d.setDate(d.getDate()+delta*(calendarMode==='week'?7:1));selectedDate=iso(d);month=d.getMonth();year=d.getFullYear();}else{const d=new Date(year,month+delta,1);month=d.getMonth();year=d.getFullYear();}render();return;}
 if(action==='calendar-today'){selectedDate=today;month=8;year=2026;render();return;}
 if(action==='calendar-mode'){calendarMode=value;render();return;}
 if(action==='select-date'){selectedDate=el.dataset.date;month=Number(selectedDate.slice(5,7))-1;year=Number(selectedDate.slice(0,4));render();return;}
 if(action==='day-detail'){selectedDate=el.dataset.date;render();const events=calendarTaskList(selectedDate);openOverlay(`<section class="drawer" role="dialog" aria-modal="true" aria-label="当天安排"><div class="drawer-top"><span>${selectedDate} · 当天安排</span><button class="icon-btn" data-action="close" aria-label="关闭">${ico('x')}</button></div><div class="drawer-content">${events.map(row).join('')||'<p class="muted">这一天暂无安排</p>'}<button class="btn primary" data-action="new-task" style="margin-top:24px">${ico('plus')}添加任务</button></div></section>`);return;}
 if(action==='save-detail'){const form=document.getElementById('detail-form'),data=new FormData(form),t=tasks.find(t=>t.id===id);if(!form.reportValidity())return;const scheduleError=validateSchedule(String(data.get('date')||''),String(data.get('time')||''),String(data.get('end')||''));if(scheduleError){document.getElementById('detail-error').textContent=scheduleError;(data.get('end')?document.getElementById('detail-end'):data.get('time')?document.getElementById('detail-date'):document.getElementById('detail-time')).focus();return;}const selectedProject=String(data.get('projectId')||'');if(t.source==='personal'&&selectedProject&&!projectStore.find(selectedProject)){showToast('所选项目已不存在，请重新选择');return;}const old={...t};for(const key of ['status','priority','date','time','end','notes'])t[key]=String(data.get(key)||'');if(t.source==='personal')t.projectId=selectedProject||null;closeOverlay();render();showToast('个人安排已保存',()=>{Object.assign(t,old);render();});return;}
 if(action==='app-filter'){window.appCategory=value;render();return;}
 if(action==='star-app'){const app=window.demoApps.find(a=>a.id===id);app.favorite=!app.favorite;render();return;}
 if(action==='new-app'||action==='edit-app'){appForm(id);return;}
 if(action==='remove-app'){const old=[...window.demoApps];window.demoApps=window.demoApps.filter(a=>a.id!==id);closeOverlay();render();showToast('应用入口已移除',()=>{window.demoApps=old;render();});return;}
 if(action==='zentao-manage'){closeOverlay();secondaryPages.activateSettingsTab('auth');showToast('请先配置禅道服务地址');return;}
 if(action==='remote-preview'){openOverlay(`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="remote-title"><h2 id="remote-title">禅道操作</h2><div class="notice">执行 #${id.slice(2)} · 禅道开源版 22.0</div><p>尚未连接禅道。连接后将根据执行状态与账号权限显示可用操作。</p><p>远端变更前将显示修改内容，确认后执行。</p><div class="modal-actions"><button class="btn" data-action="close">返回</button><button class="btn primary" data-action="zentao-manage">配置连接</button></div></section>`,true);return;}
 if(action==='test-connection')return;
});
document.addEventListener('change',event=>{const target=event.target;if(target.id==='project-filter')projectFilter=target.value;else if(target.id==='source-filter')sourceFilter=target.value;else if(target.id==='status-filter')statusFilter=target.value;else if(target.id==='priority-filter')priorityFilter=target.value;else if(target.dataset.calendarSource)calendarSources[target.dataset.calendarSource]=target.checked;else if(target.id==='management-toggle'){managementEnabled=target.checked;showToast(managementEnabled?'管理入口已开启，待连接后核验权限':'已关闭禅道管理入口');return;}else return;render();});
document.getElementById('global-search').addEventListener('input',event=>{window.searchTerm=event.target.value;if(route==='overview'&&window.searchTerm){route='tasks';history.replaceState(null,'','#tasks');}render();});
document.addEventListener('submit',event=>{
 event.preventDefault();const form=event.target,data=new FormData(form);
 if(form.id==='app-form'&&data.get('category')&&!window.appCategories.includes(data.get('category'))){document.getElementById('app-error').textContent='所选分类已不存在，请重新选择';return;}
 if(form.id==='new-task-form'){const title=String(data.get('title')).trim(),projectId=String(data.get('projectId')||''),date=String(data.get('date')||''),time=String(data.get('time')||''),end=String(data.get('end')||'');if(!title)return;const scheduleError=validateSchedule(date,time,end);if(scheduleError){document.getElementById('new-task-error').textContent=scheduleError;(end?document.getElementById('new-end'):time?document.getElementById('new-date'):document.getElementById('new-time')).focus();return;}if(projectId&&!projectStore.find(projectId)){showToast('所选项目已不存在，请重新选择');return;}tasks.push({id:'T-'+Date.now(),title,source:'personal',status:data.get('status'),priority:'normal',date,time,end,due:'',projectId:projectId||null,notes:data.get('notes'),sub:data.get('notes')||'个人任务'});closeOverlay();render();showToast('任务已创建');}
 if(form.id==='app-form'){let url;try{url=new URL(String(data.get('url')));if(!['http:','https:'].includes(url.protocol))throw new Error();}catch{document.getElementById('app-error').textContent='请输入有效的 http 或 https 网址';return;}const name=String(data.get('name')).trim();if(!name){document.getElementById('app-error').textContent='请输入应用名称';return;}const old=window.demoApps.find(a=>a.id===form.dataset.id);const file=data.get('logo');if(file?.size>2*1024*1024){document.getElementById('app-error').textContent='Logo 图片请小于 2 MB';return;}const next={id:old?.id||'app-'+Date.now(),name,description:String(data.get('description')||'').trim(),url:url.href,category:data.get('category'),logo:file?.size?URL.createObjectURL(file):old?.logo||'',favorite:old?.favorite||false};if(old)Object.assign(old,next);else window.demoApps.push(next);closeOverlay();render();showToast('应用已保存');}
 if(form.id==='connection-form'){document.getElementById('zentao-token').value='';showToast('当前为设计预览，未发起连接，也未保存凭据');}
});
document.addEventListener('keydown',event=>{const overlay=document.querySelector('.overlay');if(event.key==='Escape')closeOverlay();if(event.key==='Enter'&&event.target.matches('[data-action]:not(button):not(a):not(input):not(select)'))event.target.click();if(event.key==='Tab'&&overlay){const focusables=[...overlay.querySelectorAll('button,input,textarea,select,a')].filter(el=>!el.disabled),first=focusables[0],last=focusables.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}});
let draggedId=null;
document.addEventListener('dragstart',event=>{const item=event.target.closest('[data-task-id]');if(!item)return;draggedId=item.dataset.taskId;event.dataTransfer.setData('text/plain',draggedId);event.dataTransfer.effectAllowed='move';});
document.addEventListener('dragover',event=>{const zone=event.target.closest('[data-drop-status],[data-drop-date]');if(zone){event.preventDefault();zone.classList.add('drag-over');}});
document.addEventListener('dragleave',event=>{event.target.closest('[data-drop-status],[data-drop-date]')?.classList.remove('drag-over');});
document.addEventListener('dragend',()=>{draggedId=null;document.querySelectorAll('.drag-over').forEach(el=>el.classList.remove('drag-over'));});
document.addEventListener('drop',event=>{const zone=event.target.closest('[data-drop-status],[data-drop-date]');if(!zone)return;event.preventDefault();const id=event.dataTransfer.getData('text/plain')||draggedId,t=tasks.find(t=>t.id===id);if(!t)return;if(zone.dataset.dropStatus)changeStatus(id,zone.dataset.dropStatus);else{const old=t.date;t.date=zone.dataset.dropDate;render();showToast(`已安排在${dateLabel(t.date)}`,()=>{t.date=old;render();});}});
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(['overview','projects','tasks','calendar','apps','settings','models','agents','skills','knowledge','chat'].includes(next)){route=next;render();main.scrollTop=0;}});
route=['overview','projects','tasks','calendar','apps','settings','models','agents','skills','knowledge','chat'].includes(location.hash.slice(1))?location.hash.slice(1):'overview';
if(new URLSearchParams(location.search).get('platform')==='windows'){document.body.classList.add('platform-windows');document.querySelector('.windowbar').insertAdjacentHTML('beforeend',`<div class="windows-controls" aria-hidden="true"><span>${ico('minus')}</span><span>${ico('square')}</span><span>${ico('x')}</span></div>`);}
render();
