// 用 agent-browser eval --stdin 运行；完成后刷新恢复示例数据。
(async () => {
  const results=[];
  const check=(name,value)=>{if(!value)throw Error(name);results.push(name);};
  const click=selector=>document.querySelector(selector).click();
  const row=name=>[...document.querySelectorAll('.category-row')].find(form=>form.dataset.categoryOriginal===name);
  const add=name=>{document.getElementById('category-new-name').value=name;document.getElementById('category-new-form').requestSubmit();};
  location.hash='apps';
  await new Promise(resolve=>setTimeout(resolve,40));
  appForm();
  const parent=document.querySelector('#app-form');
  parent.elements.name.value='草稿应用';
  parent.elements.url.value='https://example.com';
  parent.elements.description.value='保留这段描述';
  const transfer=new DataTransfer();
  transfer.items.add(new File(['draft-logo'],'draft-logo.png',{type:'image/png'}));
  parent.elements.logo.files=transfer.files;
  const logo=parent.elements.logo.files[0];
  document.querySelector('[data-category-action=open]').focus();
  click('[data-category-action=open]');
  check('仅显示分类弹窗',!document.querySelector('#app-form')&&document.querySelectorAll('[role=dialog]').length===1);
  check('显示三个初始分类',document.querySelectorAll('.category-row').length===3);
  add('测试分类');
  check('新增分类',appCategories.includes('测试分类'));
  add(' 测试分类 ');
  check('拦截重复名称',document.querySelector('#category-error').textContent.includes('已存在')&&appCategories.length===4);
  add('收藏');
  check('拦截系统名称',document.querySelector('#category-error').textContent.includes('系统筛选'));
  add('   ');
  check('拦截空白名称',document.querySelector('#category-error').textContent.includes('请输入'));
  window.appCategory='开发工具';
  row('开发工具').elements.name.value='研发 & 工具';
  row('开发工具').requestSubmit();
  check('改名同步所有引用',demoApps.filter(app=>app.category==='研发 & 工具').length===5&&!demoApps.some(app=>app.category==='开发工具'));
  check('改名同步当前筛选',window.appCategory==='研发 & 工具');
  check('动态名称正确转义',document.querySelector('[data-value="研发 & 工具"]').textContent==='研发 & 工具');
  row('研发 & 工具').querySelector('[data-category-action=delete]').click();
  click('[data-category-action=confirm-delete]');
  check('删除使用中分类必须选择替代项',appCategories.includes('研发 & 工具')&&document.querySelector('#category-error').textContent.includes('请选择'));
  const replacement=document.querySelector('#category-replacement');
  replacement.value=[...replacement.options].find(option=>option.textContent==='测试分类').value;
  click('[data-category-action=confirm-delete]');
  check('删除并迁移应用',!appCategories.includes('研发 & 工具')&&demoApps.filter(app=>app.category==='测试分类').length===5);
  check('删除后筛选切换目标分类',window.appCategory==='测试分类');
  click('.category-manager .modal-actions [data-action=close]');
  check('恢复原表单节点',document.querySelector('#app-form')===parent);
  check('草稿字段保持',parent.elements.name.value==='草稿应用'&&parent.elements.description.value==='保留这段描述');
  check('Logo文件保持',parent.elements.logo.files[0]===logo);
  check('父表单分类更新',parent.elements.category.value==='测试分类');
  check('焦点返回管理链接',document.activeElement.matches('[data-category-action=open]'));
  click('[data-category-action=open]');
  document.querySelector('.category-manager button').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
  check('Escape只关闭分类弹窗',document.querySelector('#app-form')===parent&&!categoryManager.isOpen());
  click('[data-category-action=open]');
  click('.overlay');
  check('遮罩只关闭分类弹窗',document.querySelector('#app-form')===parent&&!categoryManager.isOpen());
  click('[data-category-action=open]');
  for(const name of [...appCategories]){
    row(name).querySelector('[data-category-action=delete]').click();
    const select=document.querySelector('#category-replacement');
    if(select)select.value='none';
    click('[data-category-action=confirm-delete]');
  }
  check('可清空分类并保留应用',appCategories.length===0&&demoApps.length===12&&demoApps.every(app=>!app.category));
  click('.category-manager .modal-actions [data-action=close]');
  check('没有分类时可选未分类',parent.elements.category.value===''&&parent.elements.category.options.length===1);
  parent.elements.logo.value='';
  parent.requestSubmit();
  check('原应用草稿可继续保存',demoApps.at(-1).name==='草稿应用'&&demoApps.at(-1).category==='');
  return {passed:results.length,results};
})()
