// 在 agent-browser eval --stdin 中运行；仅修改当前预览会话，运行后刷新恢复示例。
(async () => {
  const results = [];
  const check = (name, condition) => {
    if (!condition) throw new Error(name);
    results.push(name);
  };
  const click = selector => {
    const element = document.querySelector(selector);
    if (!element) throw new Error(`未找到 ${selector}`);
    element.click();
  };
  const action = (name, id) => click(`[data-project-action="${name}"]${id ? `[data-project-id="${id}"]` : ''}`);
  const fill = (selector, value) => { document.querySelector(selector).value = value; };
  const tick = () => new Promise(resolve => setTimeout(resolve, 30));
  const go = async page => { closeOverlay(); navigate(page); await tick(); };
  await go('projects');
  check('项目初始数量与来源', projectStore.projects.length === 7 && document.querySelectorAll('.project-list-row').length === 7);
  action('filter', 'zentao');
  check('禅道来源筛选', document.querySelectorAll('.project-list-row').length === 4);
  action('filter', 'local');
  check('本地来源筛选', document.querySelectorAll('.project-list-row').length === 3);
  action('filter', 'all');
  action('new');
  fill('#project-name', '客户门户');
  fill('#project-description', '验证同名项目隔离');
  document.querySelector('#project-editor-form').requestSubmit();
  const local = projectStore.projects.at(-1);
  check('同名本地项目保持独立 ID', local.source === 'local' && local.id !== 'zt-project-12' && local.name === '客户门户');
  action('detail', local.id);
  action('new-task', local.id);
  check('项目内新任务默认关联', document.querySelector('#new-project').value === local.id);
  fill('#new-title-input', '项目关联回归任务');
  document.querySelector('#new-task-form').requestSubmit();
  const task = projectTaskAPI.getTasks().at(-1);
  check('创建任务关联与来源', task.projectId === local.id && task.source === 'personal');
  action('tasks', local.id);
  await tick();
  check('查看项目看板过滤', document.querySelector('#project-filter').value === local.id && filteredTasks().length === 1);
  projectTaskAPI.openTask(task.id);
  fill('#detail-project', 'zt-project-12');
  click('[data-action="save-detail"]');
  check('个人任务可关联禅道项目且不改变来源', task.projectId === 'zt-project-12' && task.source === 'personal');
  check('移动后原项目不含该任务', filteredTasks().length === 0);
  await go('projects');
  const remoteRow = document.querySelector('[data-project-action="detail"][data-project-id="zt-project-12"]').closest('.project-list-row');
  check('目标项目计数更新', remoteRow.querySelector('.project-task-link').textContent.includes('4 项任务'));
  projectTaskAPI.openTask('E-238');
  check('禅道所属项目没有可编辑字段', !document.querySelector('#detail-project') && document.querySelector('.task-project-readonly').textContent.includes('#12'));
  const injected = document.createElement('input');
  injected.name = 'projectId'; injected.value = local.id;
  document.querySelector('#detail-form').append(injected);
  click('[data-action="save-detail"]');
  const remoteTask = projectTaskAPI.getTasks().find(item => item.id === 'E-238');
  check('伪造表单不改变远端项目关联', remoteTask.projectId === 'zt-project-12' && remoteTask.remoteProjectId === 12);
  action('edit', 'local-workbench');
  fill('#project-name', '工作台新名称');
  document.querySelector('#project-editor-form').requestSubmit();
  check('改名后任务展示更新且 ID 保持', projectTaskAPI.getTasks().find(item => item.id === 'T-106').project === '工作台新名称');
  action('edit', 'local-workbench');
  action('delete', 'local-workbench');
  check('关联任务阻止项目删除', !!projectStore.find('local-workbench') && document.querySelector('#project-editor-form') !== null);
  closeOverlay();
  action('tasks', local.id);
  await tick();
  check('空项目筛选生效', filteredTasks().length === 0);
  await go('projects');
  action('edit', local.id);
  action('delete', local.id);
  action('confirm-delete', local.id);
  check('空本地项目确认后删除', !projectStore.find(local.id));
  await go('tasks');
  check('删除筛选项目后恢复全部任务', document.querySelector('#project-filter').value === 'all' && filteredTasks().length === 13);
  click('[data-action="task-view"][data-value="list"]');
  projectTaskAPI.openTasks('zt-project-12');
  check('项目看板入口切回看板', !!document.querySelector('[data-drop-status="todo"]'));
  await go('projects');
  action('sync');
  check('同步明确未连接', document.querySelector('.modal').textContent.includes('尚未执行同步') && document.querySelector('.modal a').getAttribute('href') === '#settings');
  closeOverlay();
  await go('tasks');
  projectTaskAPI.openTasks('zt-project-12');
  const previous = remoteTask.status;
  const transfer = new DataTransfer(); transfer.setData('text/plain', 'E-238');
  document.querySelector('[data-drop-status="done"]').dispatchEvent(new DragEvent('drop', {bubbles:true, cancelable:true, dataTransfer:transfer}));
  check('拖拽只改变个人状态', remoteTask.status === 'done' && remoteTask.remote === '进行中' && remoteTask.projectId === 'zt-project-12');
  click('[data-action="undo"]');
  check('撤销恢复个人状态', remoteTask.status === previous);
  await go('apps');
  check('应用导航正常', document.querySelector('h1').textContent === '应用');
  await go('chat');
  check('聊天导航正常', document.querySelector('#main').textContent.includes('会话'));
  await go('projects');
  return {passed:results.length, results};
})()
