// 浏览器集成检查会修改示例数据；完成后刷新恢复。文件仅验证添加流程，不验证格式解析。
(async()=>{
  const results=[];
  const check=(name,condition)=>{if(!condition)throw Error(name);results.push(name);};
  const click=selector=>{const target=document.querySelector(selector);if(!target)throw Error(`未找到 ${selector}`);target.click();};
  const fill=(selector,value)=>{const target=document.querySelector(selector);target.value=value;target.dispatchEvent(new Event('input',{bubbles:true}));};
  const change=(selector,value)=>{document.querySelector(selector).value=value;document.querySelector(selector).dispatchEvent(new Event('change',{bubbles:true}));};
  const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  const go=async page=>{closeOverlay();location.hash=page;await wait(40);};
  const files=(selector,items)=>{const input=document.querySelector(selector),transfer=new DataTransfer();items.forEach(file=>transfer.items.add(file));input.files=transfer.files;input.dispatchEvent(new Event('change',{bubbles:true}));};
  await go('skills');
  check('技能和知识库导航',!!document.querySelector('a[href="#skills"]')&&!!document.querySelector('a[href="#knowledge"]'));
  click('[data-skill-action=create]');fill('#skill-name','需求整理');fill('#skill-content','整理需求与验收条件。');document.querySelector('#skill-form').requestSubmit();
  const createdSkill=resourceStore.skills.at(-1);
  check('创建技能',createdSkill.name==='需求整理'&&createdSkill.source==='local');
  click('[data-skill-action=import]');
  files('#skill-import-file',[new File(['---\nname: 周报整理\ndescription: 汇总本周工作\n---\n# 周报\n<img src=x onerror=alert(1)>\n保持事实准确。'],'SKILL.md',{type:'text/markdown'})]);
  await wait(80);
  check('技能导入先预览',document.querySelector('#skill-import-preview').textContent.includes('周报整理')&&!document.querySelector('#skill-import-preview img'));
  click('[data-skill-action=confirm-import]');
  const imported=resourceStore.skills.at(-1);
  check('Markdown技能确认导入',imported.source==='imported'&&imported.name==='周报整理');
  click('[data-skill-action=import]');files('#skill-import-file',[new File(['{"name":'],'broken.json')]);await wait(80);
  check('无效JSON禁止导入',document.querySelector('#skill-import-confirm').disabled&&document.querySelector('#skill-import-error').textContent.includes('JSON'));
  closeOverlay();
  agentPages.openEditor('planner');
  document.querySelector(`[name=skillIds][value="${imported.id}"]`).checked=true;
  document.querySelector('#agent-form').requestSubmit();
  check('Agent关联技能',aiStore.agents.find(a=>a.id==='planner').skillIds.includes(imported.id));
  click(`[data-skill-action=delete][data-id="${imported.id}"]`);
  check('被Agent引用技能禁止删除',!!resourceStore.skills.find(s=>s.id===imported.id)&&!document.querySelector('#skill-delete-title'));
  await go('knowledge');
  click('[data-knowledge-action=new]');
  check('知识库仅可选启用向量模型',[...document.querySelector('#knowledge-model').options].every(option=>resourceStore.embeddingModels().some(({provider,model})=>JSON.stringify([provider.id,model.id])===option.value)));
  fill('#knowledge-name','项目资料');fill('#knowledge-description','项目说明与业务文档');document.querySelector('#knowledge-form').requestSubmit();
  const kb=resourceStore.knowledgeBases.at(-1);
  check('新增独立知识库',kb.name==='项目资料'&&kb.providerId==='local'&&kb.modelId==='qwen-embed');
  knowledgePages.openDetail(kb.id);await wait(40);
  const uploaded=['ppt','pptx','doc','docx','xls','xlsx','txt','md','pdf'].map(type=>new File(['sample content'],`示例.${type}`));
  files('#knowledge-file-input',uploaded);
  check('九类文件可加入库内',kb.documents.length===9&&kb.documents.every(doc=>doc.file instanceof File));
  check('全部待解析且不伪造索引',kb.documents.every(doc=>doc.status==='pending')&&document.querySelector('.knowledge-footer').textContent.includes('尚未上传'));
  files('#knowledge-file-input',[uploaded[0],new File(['unsupported'],'run.exe'),new File([],'empty.pdf')]);
  check('拒绝重复空文件和不支持格式',kb.documents.length===9&&document.querySelector('.knowledge-upload-result').textContent.includes('文件为空')&&document.querySelector('.knowledge-upload-result').textContent.includes('格式不支持'));
  files('#knowledge-file-input',[new File([new Uint8Array(30*1024*1024+1)],'large.pdf')]);
  check('文件大小限制',kb.documents.length===9&&document.querySelector('.knowledge-upload-result').textContent.includes('30 MB'));
  chatPages.start('planner');await wait(40);
  const conversation=aiStore.conversations[0];
  check('新会话保留技能快照',conversation.config.skillsSnapshot.some(skill=>skill.id===imported.id));
  const priorContent=conversation.config.skillsSnapshot.find(skill=>skill.id===imported.id).content;
  imported.content='修改后的指令';
  check('技能编辑不改历史配置',conversation.config.skillsSnapshot.find(skill=>skill.id===imported.id).content===priorContent);
  change('#chat-knowledge-select',kb.id);
  fill('#chat-input','请根据资料整理要点');
  change('#chat-knowledge-select','kb-work');change('#chat-knowledge-select',kb.id);
  check('切换知识库保留输入草稿',document.querySelector('#chat-input').value==='请根据资料整理要点');
  document.querySelector('#chat-form').requestSubmit();
  check('生成期间锁定知识库选择',document.querySelector('#chat-knowledge-select').disabled);
  await wait(1250);
  check('消息保留知识库快照',conversation.messages.every(message=>message.knowledge?.id===kb.id));
  check('回复明确未检索',conversation.messages.at(-1).demo&&conversation.messages.at(-1).content.includes('没有检索文档'));
  change('#chat-knowledge-select','kb-work');
  check('换库不改变历史消息',conversation.messages[0].knowledge.name==='项目资料');
  await go('knowledge');knowledgePages.openDetail(kb.id);
  click('[data-knowledge-action=edit]');click('[data-knowledge-action=delete]');
  check('历史消息引用知识库禁止删除',!!document.querySelector('#knowledge-form')&&!!resourceStore.findKnowledge(kb.id));
  await go('models');click('[data-model-action=select][data-id=local]');click('[data-model-action=remove-model][data-id=qwen-embed]');
  check('向量模型引用删除保护',!document.querySelector('#model-remove-title')&&!!aiStore.providers.find(p=>p.id==='local').models.find(m=>m.id==='qwen-embed'));
  click('[data-model-action=edit-model][data-id=qwen-embed]');fill('#model-id-input','different-embedding');document.querySelector('#model-edit-form').requestSubmit();
  check('引用向量模型禁止换远端ID',document.querySelector('#model-edit-error').textContent.includes('知识库引用'));
  closeOverlay();click('[data-model-toggle=qwen-embed]');
  await go('chat');
  check('模型停用使所选知识库不可用',document.querySelector('#chat-input').disabled&&document.querySelector('.chat-unavailable').textContent.includes('向量模型不可用'));
  change('#chat-knowledge-select','');
  check('可取消知识库恢复普通聊天',!document.querySelector('#chat-input').disabled);
  await go('models');click('[data-model-toggle=qwen-embed]');
  await go('knowledge');knowledgePages.openDetail(kb.id);click('[data-knowledge-action=remove-file]');
  check('移除文件需确认',!!document.querySelector('#knowledge-remove-title')&&kb.documents.length===9);
  click('[data-knowledge-action=confirm-remove-file]');check('确认后移除文档',kb.documents.length===8);
  return {passed:results.length,results};
})()
